# Configuration file of class SecurityDiscoveryModule

# Name  InputDirectory
# Type  java.nio.Path
# Desc  The path to the diretory where files with new Security names can be found.
# Para  1: user home directory
#       2: curret directory
# Dflt  (none)
InputDirectory: %1$s/.coratrade/security.in/
