# Configuration of object CoraTrade

# name  DatabaseType
# desc  type of HSQL db
# type  String
# dflt  "file"
DatabaseType = "file"

# name  DatabaseLocation
# desc  path to the database
# type  File
# dflt  ~/.coratrade/db
DatabaseLocation = ~/.coratrade/db

# name  DatabaseUsername
# desc  DB user name
# type  String
# dflt  "sa"
DatabaseUsername = "sa"

# name  DatabasePassword
# desc  Db password
# type  String
# dflt  ""
DatabasePassword = ""
